# Chatterbox TTS Configuration
# This file contains user-configurable settings for the TTS system

# Server Configuration
server:
  host: "0.0.0.0"
  port: 2049
  workers: 1
  reload: false
  log_level: "INFO"

# Voice Configuration
voices:
  default: "microsoft_speecht5"
  available:
    microsoft_speecht5:
      name: "Microsoft SpeechT5"
      model: "microsoft/speecht5_tts"
      vocoder: "microsoft/speecht5_hifigan"
      speaker_embedding: "default"
      language: "en-US"
      gender: "neutral"
      speed: 1.0
      pitch: 1.0
      description: "High-quality neural TTS model"
    
    coqui_tts:
      name: "Coqui TTS"
      model: "tts_models/en/ljspeech/tacotron2-DDC"
      vocoder: "vocoder_models/en/ljspeech/hifigan_v2"
      language: "en"
      speed: 1.0
      pitch: 1.0
      description: "Open-source TTS model"

# Processing Configuration
processing:
  chunk_size: 1000  # Characters per chunk for large documents
  max_chunk_size: 2000
  overlap_size: 50  # Characters overlap between chunks
  stitch_audio: true  # Automatically stitch audio chunks
  crossfade_duration: 0.5  # Seconds for crossfade between chunks
  
# Audio Configuration
audio:
  sample_rate: 22050
  bit_depth: 16
  channels: 1
  format: "wav"
  quality: "high"  # high, medium, low

# Storage Configuration
storage:
  base_directory: "~/chatterbox_tts"
  
  paths:
    voices:
      default: "./voices/default"
      custom: "./voices/custom"
      downloaded: "./voices/downloaded"
    
    processing:
      input: "./input"
      output: "./output"
      temp: "./temp"
      logs: "./logs"
    
    cache:
      models: "./cache/models"
      audio: "./cache/audio"
    
    backups:
      location: "./backups"
      retention_days: 30

# API Configuration
api:
  cors_origins: ["http://localhost:3000", "http://localhost:8080", "http://localhost:2049"]
  max_file_size: 100  # MB
  request_timeout: 300  # seconds
  rate_limit: "100/minute"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/chatterbox.log"
  max_size: "10MB"
  backup_count: 5

# Advanced Configuration
advanced:
  gpu_enabled: true
  gpu_memory_fraction: 0.8
  preload_models: true
  cleanup_temp_files: true
  enable_metrics: false